apiVersion: v1
data:
  alertmanager.yaml: Imdsb2JhbCI6CiAgInJlc29sdmVfdGltZW91dCI6ICI1bSIKInJlY2VpdmVycyI6Ci0gIm5hbWUiOiAibnVsbCIKInJvdXRlIjoKICAiZ3JvdXBfYnkiOgogIC0gImFsZXJ0bmFtZSIKICAtICJuYW1lc3BhY2UiCiAgImdyb3VwX2ludGVydmFsIjogIjVtIgogICJncm91cF93YWl0IjogIjMwcyIKICAicmVjZWl2ZXIiOiAibnVsbCIKICAicmVwZWF0X2ludGVydmFsIjogIjEyaCIKICAicm91dGVzIjoKICAtICJtYXRjaCI6CiAgICAgICJhbGVydG5hbWUiOiAiV2F0Y2hkb2ciCiAgICAicmVjZWl2ZXIiOiAibnVsbCI=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: kubesphere-monitoring-system
type: Opaque
