apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - interval: 1m
    port: http
  selector:
    matchLabels:
      app: grafana
