apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.9.4
  name: kube-state-metrics
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    port: http-metrics
    relabelings:
    - action: labeldrop
      regex: (service|endpoint)
    scrapeTimeout: 30s
  - interval: 1m
    port: telemetry
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/version: v1.9.4
